### ISSUE TITLE
Timebox Evo support

### ISSUE THREAD

**Issue by digicide** [mumpitzstuff/fhem-Divoom#2]
Reading through your [thread on fhem](https://forum.fhem.de/index.php?topic=81593.0), it seems like you've made some progress on sending pictures to Timebox Evo. Will you be adding those enhancements to this repo?

**Comment by schwatter** [comment]
Mumpitzstuff added 3 months ago support. Look at the last commits. You have to set 

`my $escaped = 0;`

Because i figured out, that timeboxEvo send no hello.

**Comment by digicide** [comment]
Thanks for your reply and your work on this. I did look through that commit first–it seems to be about switching ports, toggling escaping, and disabling the hello.

When I read the forum thread, it looks like the two of you made significant progress on sending images to Evo around 5 December. Your code uses a convertImageTBEVO function that doesn't appear in this repository. Since the thread then moved on to animation I assumed you had images figured out. Maybe you only got two-color images working?

**Comment by schwatter** [comment]
I see, it is not the last version on github. Use the one from the thread, It is a bit cleaned up from him.

https://forum.fhem.de/index.php/topic,81593.msg868319.html#msg868319

Till yet picturesending for evo is ok. Animation not yet because the structure is another. But raw
sniffing and sending work for almost all (pictures, animations).

To send a picture you need 4 things:
1. the divoom.pl
2. a picture that fit with right color and depth.(16x16-32bit)
3. the right depencies for perl from thread
4. an extra script that call the divoom.pl with picturesendingdetails

Here some example from me. It is some small loop to simulate some animation.

https://www.dropbox.com/s/53y7dupuntckan1/setPictureTbEvo.pl?dl=0

**Comment by mumpitzstuff** [comment]
Updated the repo to the latest version. Sry but i can not provide an animation upload feature because i do not have the time to implement it.

**Comment by digicide** [comment]
Thank you! These files are very helpful. I wasn't able to get bluetooth going in perl on my Mac, but I ported everything to swift and most images are working. Maybe 20% of images are failing and I'm not sure why.

Would one of you mind confirming that the 'tb_evo.png' image works? When I send this with my swift app I get pixel salad and I'm trying to isolate whether it's my bluetooth communication or the command itself. Is this command correct? Does it work when sent via the perl script? Thanks…

tb_evo.png raw command, as generated by perl script in this repo:
01440144000A0A04AA2D0000000012000000FFFFFF0000FF0000F8FFFF00F8F800DDDD00F8FF00DDFF00DB0000FAFFFFF70000FF0505DC0303DC0000F70404FF0404FFFFF8000000000000000100000002030303000000000200000000000000000000020000000000000004050504000000000200000000000004050505050400000000000100000004000000000000040000010000000004050004000004000504000000000000050605060505060506050000000000000506060506060506060500000200000004060500040400050604000000000000000405000000000507000000000000000000040505050508090a0b010000000c000c0004050507090d0e0d0b00000c0d0f0d0c000000000a090d090a000000100d100000000000010a0b0a11020000000c000000000000000000000000000000000000000000000000000000001D1F02

**Comment by mumpitzstuff** [comment]
Sry i do not own a Timebox Evo. May be @schwatter can help.

**Comment by schwatter** [comment]
@digicide 
yes you're right. The png do pixelsalad. Here is some skull.png that work for me.

https://www.dropbox.com/s/3ntvn7mpt6jcnk6/tb_evo%20%282%29.png?dl=0

I noticed that problem in the past by myself. I downloaded some animation in divoomapp to internal
storage. The gif's extracted pictures are always 240x240 pixel. So when sending with mumpitzstuff's
script, big pictures get resized but blurred. After that i tried another way. Extracted all pictures and then resized all with IrfanView. Most pictures work, but there are often pictures that get pixelsalad.

So we must look, what can cause that failure.

**Comment by digicide** [comment]
@schwatter
I am not sure if we have the same issue, but I have solved my issue. It was stemming from images that have fewer than 128 colors–the conversion scripts here use 8 bits for each pixel to specify the index of its color in the palette, but I believe each pixel only uses as many bits as needed for the palette.

When there are only two colors, each pixel only gets one bit. When there are three colors, each pixel gets two bits. Many of my images use something like 77 colors which require 7 bits, so were coming across garbled when I refer to their palette index using 8 bits.

Instead of trying to dynamically change the number of bits used per pixel, I tried padding the palette out to 129 colors, by repeating black color at the end of the palette a bunch of times. All images are working properly for me now.

**Comment by digicide** [comment]
Here is the raw for tb_evo.png, using the above method. There were 18 colors in the image, padded out to 129 by adding black 111 times. That changes the palette length to 129 or 81 in hex.

01910244000A0A04AA2D0000000081000000FFFFFF0000FF0000F8FFFF00F8F800DDDD00F8FF00DDFF00DB0000FAFFFFF70000FF0505DC0303DC0000F70404FF0404FFFFF8000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000002030303000000000200000000000000000000020000000000000004050504000000000200000000000004050505050400000000000100000004000000000000040000010000000004050004000004000504000000000000050605060505060506050000000000000506060506060506060500000200000004060500040400050604000000000000000405000000000507000000000000000000040505050508090A0B010000000C000C0004050507090D0E0D0B00000C0D0F0D0C000000000A090D090A000000100D100000000000010A0B0A11020000000C00000000000000000000000000000000000000000000000000000000DA1F02

**Comment by mumpitzstuff** [comment]
should be fixed with the last commit
